# Generated by Django 4.2.23 on 2025-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=5)),
                ('target_currency', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
